# Generated by Django 6.1 on 2026-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('committee', 'Society Committee'), ('emergency', 'Emergency Service')], max_length=15)),
                ('name', models.CharField(help_text="e.g. 'Mr. Sharma' or 'City Police Station'", max_length=100)),
                ('designation', models.CharField(blank=True, help_text="e.g. 'Secretary', 'Ambulance'", max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['category', 'designation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
