# Generated by Django 6.1 on 2026-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_committee',
            field=models.BooleanField(default=False, help_text="Committee/admin member. Grants access to admin tools in addition to this person's normal resident account."),
        ),
        migrations.AddField(
            model_name='user',
            name='wing',
            field=models.CharField(blank=True, help_text='e.g. A, B, Tower-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='flat_number',
            field=models.CharField(blank=True, help_text='e.g. 101', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('flat_number__gt', '')), fields=('wing', 'flat_number'), name='unique_wing_flat_when_set'),
        ),
    ]
