# Generated by Django 6.1 on 2026-08-23 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_resident',
            field=models.ForeignKey(blank=True, help_text="Required when target is 'Specific Resident'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_type',
            field=models.CharField(choices=[('all', 'All Residents'), ('wing', 'Specific Wing'), ('resident', 'Specific Resident')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_wing',
            field=models.CharField(blank=True, help_text="Required when target is 'Specific Wing'", max_length=10),
        ),
    ]
