# Generated by Django 6.1 on 2026-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_photo',
            field=models.ImageField(blank=True, help_text="Optional 'after' photo attached when the complaint is resolved.", null=True, upload_to='complaints/resolved/%Y/%m/'),
        ),
    ]
